/**
 * Reports Service
 * Generates Classification Pack + Substance Pack for FTA audits
 * One-click exports, signed and timestamped
 */

import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Classification Pack — for FTA audit or auditor review
   * Contains: all transactions, classifications, rule versions, overrides
   */
  async generateClassificationPack(
    orgId: string,
    taxPeriodId: string,
  ): Promise<Buffer> {
    const [org, period, transactions] = await Promise.all([
      this.prisma.organization.findUnique({ where: { id: orgId } }),
      this.prisma.taxPeriod.findFirst({ where: { id: taxPeriodId, orgId } }),
      this.prisma.revenueTransaction.findMany({
        where: { orgId, taxPeriodId, isDeleted: false },
        include: {
          activityCatalog: { select: { code: true, name: true } },
          overrides: {
            orderBy: { createdAt: 'asc' },
            include: { overriddenBy: { select: { email: true } } },
          },
        },
        orderBy: { date: 'asc' },
      }),
    ]);

    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Cover page
    let page = pdfDoc.addPage([595, 842]); // A4
    const { width, height } = page.getSize();

    page.drawText('QFZP Status Protection', {
      x: 50, y: height - 80, size: 20, font: boldFont, color: rgb(0.1, 0.3, 0.7),
    });
    page.drawText('Revenue Classification Pack', {
      x: 50, y: height - 110, size: 16, font: boldFont,
    });
    page.drawText(`Organization: ${org?.name ?? orgId}`, { x: 50, y: height - 160, size: 11, font });
    page.drawText(`Trade License: ${org?.tradeLicenseNo ?? 'N/A'}`, { x: 50, y: height - 180, size: 11, font });
    page.drawText(
      `Tax Period: ${period?.startDate.toISOString().slice(0, 10)} to ${period?.endDate.toISOString().slice(0, 10)}`,
      { x: 50, y: height - 200, size: 11, font },
    );
    page.drawText(`Generated: ${new Date().toISOString()} UTC`, { x: 50, y: height - 220, size: 11, font });
    page.drawText('Rule Version: CD100-2023-v1', { x: 50, y: height - 240, size: 11, font });

    const disclaimer =
      'DISCLAIMER: This report is generated by an informational tool. It does not constitute\n' +
      'tax advice. Consult a qualified UAE Corporate Tax advisor for material decisions.';
    page.drawText(disclaimer, { x: 50, y: height - 290, size: 9, font, color: rgb(0.5, 0.5, 0.5) });

    // Summary stats
    const qi = transactions.filter((t) => t.classification === 'QI').length;
    const nqi = transactions.filter((t) => t.classification === 'NQI').length;
    const excluded = transactions.filter((t) => t.classification === 'EXCLUDED').length;
    const unclassified = transactions.filter((t) => t.classification === 'UNCLASSIFIED').length;

    page.drawText('Summary', { x: 50, y: height - 340, size: 14, font: boldFont });
    page.drawText(`Total Transactions: ${transactions.length}`, { x: 50, y: height - 360, size: 11, font });
    page.drawText(`Qualifying Income (QI): ${qi}`, { x: 50, y: height - 380, size: 11, font, color: rgb(0.1, 0.6, 0.1) });
    page.drawText(`Non-Qualifying Income (NQI): ${nqi}`, { x: 50, y: height - 400, size: 11, font, color: rgb(0.8, 0.1, 0.1) });
    page.drawText(`Excluded: ${excluded}`, { x: 50, y: height - 420, size: 11, font, color: rgb(0.5, 0.5, 0.5) });
    page.drawText(`Unclassified (REVIEW REQUIRED): ${unclassified}`, { x: 50, y: height - 440, size: 11, font });

    // Transaction details (first 50 per page)
    const ROWS_PER_PAGE = 30;
    for (let i = 0; i < transactions.length; i += ROWS_PER_PAGE) {
      const slice = transactions.slice(i, i + ROWS_PER_PAGE);
      page = pdfDoc.addPage([595, 842]);
      let y = height - 50;

      page.drawText(`Transactions (${i + 1}–${Math.min(i + ROWS_PER_PAGE, transactions.length)})`, {
        x: 50, y, size: 13, font: boldFont,
      });
      y -= 25;

      for (const tx of slice) {
        const line = [
          tx.date.toISOString().slice(0, 10),
          `AED ${parseFloat(tx.amountAed.toString()).toFixed(0)}`,
          tx.classification,
          tx.counterparty.slice(0, 25),
          tx.activityCatalog?.code ?? 'N/A',
        ].join('  |  ');

        page.drawText(line, {
          x: 50, y,
          size: 8,
          font,
          color: tx.classification === 'NQI' ? rgb(0.7, 0, 0) : rgb(0, 0, 0),
        });
        y -= 15;

        if (tx.overrides.length > 0) {
          const ov = tx.overrides[tx.overrides.length - 1];
          page.drawText(
            `  ↳ Override by ${ov.overriddenBy?.email}: ${ov.previousClassification} → ${ov.newClassification} | ${ov.reasonCode}`,
            { x: 60, y, size: 7, font, color: rgb(0.3, 0.3, 0.8) },
          );
          y -= 12;
        }

        if (y < 60) {
          page = pdfDoc.addPage([595, 842]);
          y = height - 50;
        }
      }
    }

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  }

  /**
   * Substance Pack — for FTA audit compliance proof
   */
  async generateSubstancePack(orgId: string): Promise<Buffer> {
    const [org, docs] = await Promise.all([
      this.prisma.organization.findUnique({ where: { id: orgId } }),
      this.prisma.substanceDocument.findMany({
        where: { orgId, isDeleted: false },
        orderBy: { docType: 'asc' },
      }),
    ]);

    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const page = pdfDoc.addPage([595, 842]);
    const { height } = page.getSize();

    page.drawText('QFZP Substance Document Pack', {
      x: 50, y: height - 80, size: 18, font: boldFont, color: rgb(0.1, 0.3, 0.7),
    });
    page.drawText(`Organization: ${org?.name ?? orgId}`, { x: 50, y: height - 130, size: 11, font });
    page.drawText(`Generated: ${new Date().toISOString()} UTC`, { x: 50, y: height - 150, size: 11, font });
    page.drawText(`Total documents on file: ${docs.length}`, { x: 50, y: height - 170, size: 11, font });

    let y = height - 220;
    for (const doc of docs) {
      const status = doc.status;
      const color = status === 'ACTIVE' ? rgb(0.1, 0.6, 0.1) : rgb(0.8, 0.1, 0.1);

      page.drawText(`${doc.displayName}`, { x: 50, y, size: 10, font: boldFont });
      y -= 14;
      page.drawText(`  Status: ${status}  |  File: ${doc.fileName}  |  Uploaded: ${doc.uploadedAt.toISOString().slice(0, 10)}`, {
        x: 50, y, size: 9, font, color,
      });
      if (doc.expiresAt) {
        y -= 12;
        page.drawText(`  Expires: ${doc.expiresAt.toISOString().slice(0, 10)}`, {
          x: 50, y, size: 9, font,
        });
      }
      y -= 20;

      if (y < 100) break; // safety: don't overflow (add more pages if needed)
    }

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  }
}
